<?php

/**
 * @file
 * Contains \Drupal\smiley\Plugin\CKEditorPlugin\Smiley.
 */

namespace Drupal\smiley\Plugin\CKEditorPlugin;

use Drupal\ckeditor\CKEditorPluginBase;
use Drupal\ckeditor\CKEditorPluginConfigurableInterface;

use Drupal\editor\Entity\Editor;

use Drupal\ckeditor\Annotation\CKEditorPlugin;

// Do not remove the line below because of:
// [Semantical Error] The annotation "@Translation" in class
use Drupal\Core\Annotation\Translation;

/**
 * Defines the "Smiley" plugin.
 * @see MetaContextual
 * @see MetaButton
 * @see MetaContextualAndButton
 *
 * @CKEditorPlugin(
 *   id = "smiley",
 *   label = @Translation("Smiley")
 * )
 */
class Smiley extends CKEditorPluginBase implements CKEditorPluginConfigurableInterface {

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginInterface::getDependencies().
   */
  public function getDependencies(Editor $editor) {
    return [];
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginInterface::getLibraries().
   */
  public function getLibraries(Editor $editor) {
    return [];
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginInterface::isInternal().
   */
  public function isInternal() {
    return FALSE;
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginInterface::getFile().
   */
  public function getFile() {
    return drupal_get_path('module', 'smiley') . '/js/plugins/smiley/plugin.js';
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginInterface::getConfig().
   */
  public function getConfig(Editor $editor) {
    $config = [
      'smiley_columns' => 7
    ];
    $settings = $editor->getSettings();
    if (isset($settings['plugins']['smiley'])) {
      $config = $settings['plugins']['smiley'];
    }

    return $config;
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginButtonsInterface::getButtons().
   */
  public function getButtons() {
    return [
      'Smiley' => [
        'label' => t('Smiley'),
        'image' => drupal_get_path('module', 'smiley') . '/js/plugins/smiley/icons/smiley.png',
      ]
    ];
  }

  /**
   * Implements \Drupal\ckeditor\Plugin\CKEditorPluginConfigurableInterface::settingsForm().
   */
  public function settingsForm(array $form, array &$form_state, Editor $editor) {
    // Defaults
    $config = [
      'smiley_columns' => 7
    ];
    $settings = $editor->getSettings();
    if (isset($settings['plugins']['smiley'])) {
      $config = $settings['plugins']['smiley'];
    }

    $form['smiley_columns'] = [
      '#title' => t('Smiley columns'),
      '#description' => t('The number of columns to be generated by the smilies matrix'),
      '#type' => 'textfield',
      '#default_value' => $config['smiley_columns'],
    ];

    return $form;
  }
}
